- name: Install virtualenv
  pip: name=virtualenv state=present
  become: True

- name: Create a virtualenvs directory
  file: path={{ ansible_env.HOME }}/.virtualenvs state=directory

- name: Install virtualenvwrapper
  pip: name=virtualenvwrapper state=present
  become: True

- name: Add some lines to .bashrc file
  lineinfile: >
    dest={{ ansible_env.HOME }}/.bashrc
    line="export WORKON_HOME={{ ansible_env.HOME }}/.virtualenvs"
    state=present
    insertafter=EOF

- name: Add virtualenvwrapper.sh to .bashrc
  lineinfile: >
    dest={{ ansible_env.HOME }}/.bashrc
    line=". /usr/local/bin/virtualenvwrapper.sh"
    state=present
    insertafter=EOF

- name: Auto activate the venv on login
  lineinfile: >
    dest=~/.bashrc
    line="workon {{ venv_name }}"
    state=present
    insertafter=EOF

- name: Auto activate the venv on login
  lineinfile: >
    dest=~/.bashrc
    line="export FLASK_APP=__init__.py"
    state=present
    insertafter=EOF