- name: Install Supervisor
  apt: name=supervisor state=present update_cache=yes
  become: True

- name: Run supervisor service
  service: name=supervisor state=started
  become: True

- name: Enable supervisor on startup
  command: "systemctl enable supervisor"
  become: True