- name: Configure the EnergyCoin explorer server
  hosts: 127.0.0.1
  connection: local
  user: vagrant
  roles:
    - supervisor
    - energycoind
    - ufw
    - virtualenv
    - application
  vars:
    - client_rpc_user: "rpcenergyuser"
    - client_rpc_password: "rpcenergypassword"
    - client_rpc_port: 22706
    - client_default_port: 22705
    - regtest: ""