# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  # Use the same key for each machine
  config.ssh.insert_key = false

  # Create the energyexplorer VM
  config.vm.define "energyexplorer" do |energyexplorer|
    energyexplorer.vm.box = "bento/ubuntu-16.04"
    energyexplorer.vm.synced_folder "..", "/energyexploder"

    energyexplorer.vm.network "forwarded_port", guest: 80, host: 8080

    energyexplorer.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end